package killswitch

import (
	"fmt"
	"strings"
)

// Mark — SO_MARK исходящих сокетов входящего прокси (D4): помеченный трафик
// имеет право покидать контейнер только через туннель ExpressVPN.
const Mark = 0x5050

// Params — вход генератора правил.
type Params struct {
	// Mode: host | socks5.
	Mode string
	// TunIface — интерфейс туннеля ExpressVPN.
	TunIface string
	// UplinkIface — uplink-TUN (режим socks5).
	UplinkIface string
	// EthIface — интерфейс контейнера.
	EthIface string
	// DockerSubnet — подсеть Docker (CIDR): клиенты прокси и API.
	DockerSubnet string
	// ProxyIP/ProxyPort — эндпоинт пользовательского SOCKS5 (режим socks5).
	ProxyIP   string
	ProxyPort int
}

func Defaults() Params {
	return Params{TunIface: "tun0", UplinkIface: "xup0", EthIface: "eth0"}
}

// Ruleset генерирует nftables-файл для атомарного применения `nft -f`:
// секции add+flush гарантируют замену таблицы inet detour без окна без защиты.
func Ruleset(p Params) string {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w("# generated by detour-agent; mode=%s", p.Mode)
	w("add table inet detour")
	w("flush table inet detour")
	w("")
	w("table inet detour {")
	w("  counter dropped_marked {}")
	if p.Mode == "socks5" {
		w("  counter dropped_egress {}")
	}
	w("")
	w("  chain output {")
	w("    type filter hook output priority filter; policy accept;")
	w("    oifname \"lo\" accept")
	// Трафик клиентов прокси: наружу — только в туннель; ответы клиентам
	// (docker-подсеть, UDP-relay и TCP отвечают с помеченных сокетов) — разрешены.
	if p.DockerSubnet != "" {
		w("    meta mark 0x%04x oifname \"%s\" ip daddr %s accept", Mark, p.EthIface, p.DockerSubnet)
	}
	w("    meta mark 0x%04x oifname \"%s\" accept", Mark, p.TunIface)
	w("    meta mark 0x%04x counter name dropped_marked drop", Mark)
	if p.Mode == "socks5" {
		// Наружу через интерфейс контейнера — только к пользовательскому
		// прокси и в docker-подсеть (ответы клиентам API/прокси).
		// К прокси-IP разрешаем любой протокол/порт: UDP ASSOCIATE выдаёт
		// relay-порт динамически.
		if p.ProxyIP != "" {
			w("    oifname \"%s\" ip daddr %s accept", p.EthIface, p.ProxyIP)
		}
		if p.DockerSubnet != "" {
			w("    oifname \"%s\" ip daddr %s accept", p.EthIface, p.DockerSubnet)
		}
		w("    oifname \"%s\" counter name dropped_egress drop", p.EthIface)
	}
	w("  }")
	w("}")
	return b.String()
}
